//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console --config eessi-transform-config.json
namespace ITSG.EESSI.Tstelle.XML.SED.S101.V4_4_1
{
    
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">834515A4-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SC.Sickness.ENUM</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"><CodeListEntry><ccts:UniqueID>E064C8C5-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID><value>01</value><definition>IR 987/2009, Art 63, 2.a</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>BF85DDD3-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID><value>02</value><definition>IR 987/2009, Art 63, 2.b</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>00D8B4DE-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID><value>03</value><definition>IR 574/72, Art. 94</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>CFEC90E9-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID><value>04</value><definition>IR 574/72, Art. 95</definition></CodeListEntry></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:UniqueID xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">834515A4-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID> <ccts:ObjectClassQualifierTerm xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SC.Sickness.ENUM</ccts:ObjectClassQualifierTerm> <ccts:BusinessProcessContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">EESSI</ccts:BusinessProcessContextValue> <ccts:OfficialConstraintContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2""><CodeListEntry><ccts:UniqueID>E064C8C5-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID><value>01</value><definition>IR 987/2009, Art 63, 2.a</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>BF85DDD3-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID><value>02</value><definition>IR 987/2009, Art 63, 2.b</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>00D8B4DE-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID><value>03</value><definition>IR 574/72, Art. 94</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>CFEC90E9-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID><value>04</value><definition>IR 574/72, Art. 95</definition></CodeListEntry></ccts:OfficialConstraintContextValue>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SLumpSumLegalCategoryType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SLumpSumLegalCategoryType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    public partial class SLumpSumLegalCategoryType
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: (01|02|03|04){1}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(01|02|03|04){1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EEE959FF-4B26-E611-80C8-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SC.Sickness.ENUM</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"><CodeListEntry><ccts:UniqueID>62647B1F-4C26-E611-80C8-000D3A22E8CD</ccts:UniqueID><value>01</value><definition>IR 987/2009, Art 64, Age 0-19</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>5DA6F629-4C26-E611-80C8-000D3A22E8CD</ccts:UniqueID><value>02</value><definition>IR 987/2009, Art 64, Age 20-64</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>85E23636-4C26-E611-80C8-000D3A22E8CD</ccts:UniqueID><value>03</value><definition>IR 987/2009, Art 64, Age 65+</definition></CodeListEntry></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:UniqueID xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">EEE959FF-4B26-E611-80C8-000D3A22E8CD</ccts:UniqueID> <ccts:ObjectClassQualifierTerm xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SC.Sickness.ENUM</ccts:ObjectClassQualifierTerm> <ccts:BusinessProcessContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">EESSI</ccts:BusinessProcessContextValue> <ccts:OfficialConstraintContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2""><CodeListEntry><ccts:UniqueID>62647B1F-4C26-E611-80C8-000D3A22E8CD</ccts:UniqueID><value>01</value><definition>IR 987/2009, Art 64, Age 0-19</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>5DA6F629-4C26-E611-80C8-000D3A22E8CD</ccts:UniqueID><value>02</value><definition>IR 987/2009, Art 64, Age 20-64</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>85E23636-4C26-E611-80C8-000D3A22E8CD</ccts:UniqueID><value>03</value><definition>IR 987/2009, Art 64, Age 65+</definition></CodeListEntry></ccts:OfficialConstraintContextValue>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SLumpSumCategoryType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SLumpSumCategoryType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    public partial class SLumpSumCategoryType
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: (01|02|03){1}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(01|02|03){1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">91DB36B1-769F-E611-80D1-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SC.Sickness</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:UniqueID xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">91DB36B1-769F-E611-80D1-000D3A22E8CD</ccts:UniqueID> <ccts:ObjectClassQualifierTerm xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SC.Sickness</ccts:ObjectClassQualifierTerm> <ccts:BusinessProcessContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">EESSI</ccts:BusinessProcessContextValue> <ccts:OfficialConstraintContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2""></ccts:OfficialConstraintContextValue>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SLumpSumCategoryArt63P2aType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SLumpSumCategoryArt63P2aType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    public partial class SLumpSumCategoryArt63P2AType
    {
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">061A9469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">061A9469-849F-E611-80D1-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.Xml.Serialization.XmlElementAttribute("lumpSumCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SLumpSumCategoryType LumpSumCategory { get; set; }
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">BA0DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SC.Sickness</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:UniqueID xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">BA0DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:UniqueID> <ccts:ObjectClassQualifierTerm xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SC.Sickness</ccts:ObjectClassQualifierTerm> <ccts:BusinessProcessContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">EESSI</ccts:BusinessProcessContextValue> <ccts:OfficialConstraintContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2""></ccts:OfficialConstraintContextValue>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SLumpSumCategoryArt63P2bType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SLumpSumCategoryArt63P2bType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    public partial class SLumpSumCategoryArt63P2BType
    {
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">BC0DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">BC0DFC2F-EBEE-E611-80D3-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.Xml.Serialization.XmlElementAttribute("lumpSumCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SLumpSumCategoryType LumpSumCategory { get; set; }
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B90DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SC.Sickness</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:UniqueID xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">B90DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:UniqueID> <ccts:ObjectClassQualifierTerm xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SC.Sickness</ccts:ObjectClassQualifierTerm> <ccts:BusinessProcessContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">EESSI</ccts:BusinessProcessContextValue> <ccts:OfficialConstraintContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2""></ccts:OfficialConstraintContextValue>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SLumpSumLegalCategoryClassType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SLumpSumLegalCategoryClassType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    public partial class SLumpSumLegalCategoryClassType
    {
        
        public enum SLumpSumLegalCategoryClassTypeItemChoiceType
        {
            
            [System.Xml.Serialization.XmlEnumAttribute("Art63p2a")]
            Art63P2A,
            
            [System.Xml.Serialization.XmlEnumAttribute("Art63p2b")]
            Art63P2B,
        }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">BB0DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">BB0DFC2F-EBEE-E611-80D3-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("lumpSumCategoryBasedPersonStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SLumpSumLegalCategoryType LumpSumCategoryBasedPersonStatus { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Art63p2a", Type=typeof(SLumpSumCategoryArt63P2AType))]
        [System.Xml.Serialization.XmlElementAttribute("Art63p2b", Type=typeof(SLumpSumCategoryArt63P2BType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public SLumpSumLegalCategoryClassTypeItemChoiceType ItemElementName { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SLumpSumLegalCategoryClassTypeItemChoiceType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    public enum SLumpSumLegalCategoryClassTypeItemChoiceType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("Art63p2a")]
        Art63P2A,
        
        [System.Xml.Serialization.XmlEnumAttribute("Art63p2b")]
        Art63P2B,
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">DE9B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SEDSpecific</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:UniqueID xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">DE9B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:UniqueID> <ccts:ObjectClassQualifierTerm xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SEDSpecific</ccts:ObjectClassQualifierTerm> <ccts:BusinessProcessContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">EESSI</ccts:BusinessProcessContextValue> <ccts:OfficialConstraintContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2""></ccts:OfficialConstraintContextValue>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GlobalNoteMonthsInventoryAcknowledgementType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GlobalNoteMonthsInventoryAcknowledgementType
    {
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">E39B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">E39B4596-7C9F-E611-80D1-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("globalIMOReferenceCreditorLiaisonBody", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlobalImoReferenceCreditorLiaisonBody { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">E49B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">E49B4596-7C9F-E611-80D1-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("globalACKIMOReferenceDebtorLiaisonBody", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlobalAckimoReferenceDebtorLiaisonBody { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">E79B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">AB59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">E79B4596-7C9F-E611-80D1-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("totalNumberIndividualClaims", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TotalNumberIndividualClaims { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">E69B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">E69B4596-7C9F-E611-80D1-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("totalNumberMonths", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TotalNumberMonths { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">3023DFF5-92D2-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">3023DFF5-92D2-EB11-80E7-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LumpSumLegalCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SLumpSumLegalCategoryClassType LumpSumLegalCategory { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">E99B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">E99B4596-7C9F-E611-80D1-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dateReceipt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DateReceipt { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EA9B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">EA9B4596-7C9F-E611-80D1-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dateSubmission", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DateSubmission { get; set; }
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">59FCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SED</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SED S101</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:UniqueID xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">59FCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID> <ccts:ObjectClassQualifierTerm xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SED</ccts:ObjectClassQualifierTerm> <ccts:BusinessProcessContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SED S101</ccts:BusinessProcessContextValue> <ccts:OfficialConstraintContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2""></ccts:OfficialConstraintContextValue>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("S101", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("S101", Namespace="http://ec.europa.eu/eessi/ns/4_4/S101")]
    public partial class S101
    {
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">05334300-9818-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">05334300-9818-E611-80EA-000C292ED0D7</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("GlobalNoteACKIMO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GlobalNoteMonthsInventoryAcknowledgementType GlobalNoteAckimo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public Www.W3.Org.Xmldsig.SignatureType Signature { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sedPackage")]
        public string SedPackage { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sedGVer")]
        public int SedGVer { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SedGVer property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SedGVerSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sedVer")]
        public int SedVer { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SedVer property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SedVerSpecified { get; set; }
    }
}
