//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console --config eessi-transform-config.json
namespace ITSG.EESSI.Tstelle.XML.SED.S103.V4_4_1
{
    
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">C3F70CDA-F5A1-E611-A960-00155D00FE00</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SEDSpecific</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:UniqueID xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">C3F70CDA-F5A1-E611-A960-00155D00FE00</ccts:UniqueID> <ccts:ObjectClassQualifierTerm xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SEDSpecific</ccts:ObjectClassQualifierTerm> <ccts:BusinessProcessContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">EESSI</ccts:BusinessProcessContextValue> <ccts:OfficialConstraintContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2""></ccts:OfficialConstraintContextValue>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GlobalNoteMonthsInventoryContestationAcknowledgementType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S103")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GlobalNoteMonthsInventoryContestationAcknowledgementType
    {
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">DAF70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">DAF70CDA-F5A1-E611-A960-00155D00FE00</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("globalIMOReferenceCreditorLiaisonBody", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlobalImoReferenceCreditorLiaisonBody { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">DBF70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">DBF70CDA-F5A1-E611-A960-00155D00FE00</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("globalCOCIMOReferenceDebtorLiaisonBody", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlobalCocimoReferenceDebtorLiaisonBody { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">DCF70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">DCF70CDA-F5A1-E611-A960-00155D00FE00</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("globalACKCOCIMOReferenceCreditorLiaisonBody", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlobalAckcocimoReferenceCreditorLiaisonBody { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">74DA249D-A5EF-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">AB59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">74DA249D-A5EF-E611-80D3-000D3A22E8CD</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("totalNumberContestations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TotalNumberContestations { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">E1F70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">E1F70CDA-F5A1-E611-A960-00155D00FE00</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dateReceipt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DateReceipt { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">E2F70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">E2F70CDA-F5A1-E611-A960-00155D00FE00</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dateSubmission", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DateSubmission { get; set; }
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">5BFCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SED</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SED S103</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:UniqueID xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">5BFCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID> <ccts:ObjectClassQualifierTerm xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SED</ccts:ObjectClassQualifierTerm> <ccts:BusinessProcessContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"">SED S103</ccts:BusinessProcessContextValue> <ccts:OfficialConstraintContextValue xmlns:ccts=""urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2""></ccts:OfficialConstraintContextValue>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("S103", Namespace="http://ec.europa.eu/eessi/ns/4_4/S103")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("S103", Namespace="http://ec.europa.eu/eessi/ns/4_4/S103")]
    public partial class S103
    {
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">90797906-9818-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("<ccts:DictionaryEntryName xmlns:ccts=\"urn:un:unece:uncefact:documentation:standar" +
            "d:CoreComponentsTechnicalSpecification:2\">90797906-9818-E611-80EA-000C292ED0D7</" +
            "ccts:DictionaryEntryName>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("GlobalNoteACKCOCIMO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GlobalNoteMonthsInventoryContestationAcknowledgementType GlobalNoteAckcocimo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public Www.W3.Org.Xmldsig.SignatureType Signature { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sedPackage")]
        public string SedPackage { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sedGVer")]
        public int SedGVer { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SedGVer property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SedGVerSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sedVer")]
        public int SedVer { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SedVer property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SedVerSpecified { get; set; }
    }
}
