//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0 using the following command:
// XmlSchemaClassGenerator.Console --config ../eessi-transform-config.json --directory /Users/svenhaude/EESSI-AS4.NET-master/source/Eu.EDelivery.AS4.Fe/ui/src/assets/pmodes/eessi-schemas --output ../XmlSchemaClassGenerator.Tests/GeneratedClasses
namespace ITSG.EESSI.Tstelle.XML.SED.S113.V4_4_1
{
    
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">E14216FF-DB27-E611-80C8-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SEDSpecific.ENUM</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"><CodeListEntry><ccts:UniqueID>39727A1D-DC27-E611-80C8-000D3A22E8CD</ccts:UniqueID><value>01</value><definition>We accept contestation</definition></CodeListEntry><CodeListEntry><ccts:UniqueID>3DDA1925-DC27-E611-80C8-000D3A22E8CD</ccts:UniqueID><value>02</value><definition>We do not accept contestation</definition></CodeListEntry></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("SourceFile:S113-4.4.0-20241203T114235")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute("ReplyCodeRPYCOCCLAIMOType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S113")]
    public partial class ReplyCodeRpycocclaimoType
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: (01|02){1}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(01|02){1}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("value", Order=0, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">F41763B4-832A-E711-80D4-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SEDSpecific</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("SourceFile:S113-4.4.0-20241203T114235")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute("ConditionalContestationRejectionType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S113")]
    public partial class ConditionalContestationRejectionType
    {
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">F51763B4-832A-E711-80D4-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">A659AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.CDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 155.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(155)]
        [System.Xml.Serialization.XmlElementAttribute("reasonNonAcceptance", Order=0, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReasonNonAcceptance { get; set; }
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">E29B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SEDSpecific</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("SourceFile:S113-4.4.0-20241203T114235")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute("MonthsInventoryClaimContestationReplyType", Namespace="http://ec.europa.eu/eessi/ns/4_4/S113")]
    public partial class MonthsInventoryClaimContestationReplyType
    {
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EB9B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("globalIMOReferenceCreditorLiaisonBody", Order=0, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlobalImoReferenceCreditorLiaisonBody { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EC9B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("globalCLAIMOReferenceCreditorLiaisonBody", Order=1, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlobalClaimoReferenceCreditorLiaisonBody { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">ED9B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("globalCOCCLAIMOReferenceDebtorLiaisonBody", Order=2, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlobalCocclaimoReferenceDebtorLiaisonBody { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">BD8020FE-C53B-E711-80D5-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("globalRPYCOCCLAIMOReferenceCreditorLiaisonBody", Order=3, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlobalRpycocclaimoReferenceCreditorLiaisonBody { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">F89B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("replyCode", Order=4, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReplyCodeRpycocclaimoType ReplyCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">F61763B4-832A-E711-80D4-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PleaseFillInFollowingIfReplyCode02", Order=5, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConditionalContestationRejectionType PleaseFillInFollowingIfReplyCode02 { get; set; }
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">FC9B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">B559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID></para>
        /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI.CC.BDT</ccts:ObjectClassQualifierTerm></para>
        /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">EESSI</ccts:BusinessProcessContextValue></para>
        /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dateSubmission", Order=6, Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DateSubmission { get; set; }
        
        public MonthsInventoryClaimContestationReplyType()
        {
            this.ReplyCode = new ReplyCodeRpycocclaimoType();
            this.PleaseFillInFollowingIfReplyCode02 = new ConditionalContestationRejectionType();
        }
    }
    
    /// <summary>
    /// <para xml:lang="en"><ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">64FCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID></para>
    /// <para xml:lang="en"><ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SED</ccts:ObjectClassQualifierTerm></para>
    /// <para xml:lang="en"><ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">SED S113</ccts:BusinessProcessContextValue></para>
    /// <para xml:lang="en"><ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"></ccts:OfficialConstraintContextValue></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("SourceFile:S113-4.4.0-20241203T114235")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute("S113", Namespace="http://ec.europa.eu/eessi/ns/4_4/S113")]
    [System.Xml.Serialization.XmlRootAttribute("S113", Namespace="http://ec.europa.eu/eessi/ns/4_4/S113")]
    public partial class S113
    {
        
        /// <summary>
        /// <para xml:lang="en"><ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2">FF9B4596-7C9F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName></para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("GlobalNoteRPYCOCCLAIMO", Order=0, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MonthsInventoryClaimContestationReplyType GlobalNoteRpycocclaimo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Signature", Order=1, Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public Www.W3.Org.Xmldsig.SignatureType Signature { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("sedPackage")]
        public string SedPackage { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("sedGVer")]
        public int SedGVerValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SedGVer property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SedGVerValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> SedGVer
        {
            get
            {
                if (this.SedGVerValueSpecified)
                {
                    return this.SedGVerValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SedGVerValue = value.GetValueOrDefault();
                this.SedGVerValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("sedVer")]
        public int SedVerValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SedVer property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SedVerValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> SedVer
        {
            get
            {
                if (this.SedVerValueSpecified)
                {
                    return this.SedVerValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SedVerValue = value.GetValueOrDefault();
                this.SedVerValueSpecified = value.HasValue;
            }
        }
        
        public S113()
        {
            this.GlobalNoteRpycocclaimo = new MonthsInventoryClaimContestationReplyType();
            this.Signature = new Www.W3.Org.Xmldsig.SignatureType();
        }
    }
}
