<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sedS082="http://ec.europa.eu/eessi/ns/4_4/S082" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" elementFormDefault="unqualified" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" targetNamespace="http://ec.europa.eu/eessi/ns/4_4/S082" version="4.4.0">
	<xsd:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="XAdES.xsd" />
	<xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xsd:simpleType name='EESSICRUniqueidentifierType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSICRIndividualClaimsCountType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AB59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:int'>
				<xsd:minInclusive value='0' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIAmountType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B759AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:double'>
				<xsd:pattern value='(([1-9][0-9]{0,9})(\.\d{2,2})?|([0]{1})(\.\d{2,2})?)' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSIEUEFTACurrencyType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AF3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>B03712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>EUR</value>
						<definition>Euro</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B13712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>BGN</value>
						<definition>Bulgarian Lev</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B23712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CZK</value>
						<definition>Czech Koruna</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B33712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>DKK</value>
						<definition>Danish Krone</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B43712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>GBP</value>
						<definition>British Pound</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B53712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HRK</value>
						<definition>Croatian Kuna</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B63712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HUF</value>
						<definition>Hungarian Forint</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B73712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>PLN</value>
						<definition>Polish Zloty</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B83712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>RON</value>
						<definition>Romanian New Leu</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B93712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>SEK</value>
						<definition>Swedish Krona</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BA3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CHF</value>
						<definition>Swiss Franc</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BB3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>ISK</value>
						<definition>Icelandic Krona</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BC3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>NOK</value>
						<definition>Norwegian Krone</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>12090942-FAAC-E711-80DB-000D3A22E8CD</ccts:UniqueID>
						<value>LTL</value>
						<definition>Lithuanian Litas</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>13090942-FAAC-E711-80DB-000D3A22E8CD</ccts:UniqueID>
						<value>LVL</value>
						<definition>Latvian Lats</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(EUR|BGN|CZK|DKK|GBP|HRK|HUF|PLN|RON|SEK|CHF|ISK|NOK|LTL|LVL){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIPaymentEUType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>98393937-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'amount' minOccurs='1' maxOccurs='1' type='sedS082:EESSIAmountType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2A3E7DCE-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'currency' minOccurs='1' maxOccurs='1' type='sedS082:EESSIEUEFTACurrencyType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2B3E7DCE-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIBusinessDateType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:date'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='GlobalNoteClaimContestationType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>FA9C44F7-F748-E611-80C9-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'globalCLAReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS082:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>FE9C44F7-F748-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalCOCReferenceDebtorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS082:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>FF9C44F7-F748-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'totalNumberOfContestations' minOccurs='1' maxOccurs='1' type='sedS082:EESSICRIndividualClaimsCountType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>FC9C44F7-F748-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'TotalAmountContestations' minOccurs='1' maxOccurs='1' type='sedS082:EESSIPaymentEUType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>019D44F7-F748-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'dateOfSubmission' minOccurs='1' maxOccurs='1' type='sedS082:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>FD9C44F7-F748-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIInstitutionIDType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B659AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:pattern value='(AT|BE|BG|HR|CY|CZ|DK|EE|FI|FR|DE|EL|HU|IS|IE|IT|LV|LI|LT|LU|MT|NL|NO|PL|PT|RO|SK|SI|ES|SE|CH|UK|EU):[a-zA-Z0-9]{4,10}' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIMediumStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A659AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='155' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSIInstitutionType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2E243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'institutionID' minOccurs='1' maxOccurs='1' type='sedS082:EESSIInstitutionIDType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>38684F61-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'institutionName' minOccurs='1' maxOccurs='1' type='sedS082:EESSIMediumStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2AAB0BC6-ACFA-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ReferencesType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>75411697-5DED-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'globalCLAReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS082:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>78411697-5DED-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalCOCReferenceDebtorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS082:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>79411697-5DED-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'individualCLANumberCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS082:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>7A411697-5DED-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'individualCOCNumberDebtorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS082:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>77411697-5DED-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIPersonNameType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B059AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='155' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIDateOfBirthType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B159AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:date'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSISexType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>4E0A4E7A-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>4F0A4E7A-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>Male</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>CAA1E7BA-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>Female</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>D797EEC3-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>98</value>
						<definition>Unknown</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|98){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIPersonValidationType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2AD172C9-7289-E611-80D0-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'familyName' minOccurs='1' maxOccurs='1' type='sedS082:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3AD172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'forename' minOccurs='1' maxOccurs='1' type='sedS082:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3BD172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'dateBirth' minOccurs='1' maxOccurs='1' type='sedS082:EESSIDateOfBirthType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3CD172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'sex' minOccurs='1' maxOccurs='1' type='sedS082:EESSISexType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>379E16FD-8890-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIPINType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AE59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='65' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSIPersonIdentificationNumberType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>91BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'pINPersonInCompetentMemberState' minOccurs='1' maxOccurs='1' type='sedS082:EESSIPINType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>9ABF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'pINPersonInMemberStateStayOrResidence' minOccurs='0' maxOccurs='1' type='sedS082:EESSIPINType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>9BBF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIPersonInfoType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>94BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'PersonInformation' minOccurs='1' maxOccurs='1' type='sedS082:EESSIPersonValidationType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>A3BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'familyNameAtBirth' minOccurs='0' maxOccurs='1' type='sedS082:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>97BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'forenameAtBirth' minOccurs='0' maxOccurs='1' type='sedS082:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>98BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'PersonIdentificationNumber' minOccurs='1' maxOccurs='1' type='sedS082:EESSIPersonIdentificationNumberType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>A4BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='SicknessContestationRefusalCodeType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>358B5D6D-A249-E611-80CA-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>0C661D19-61ED-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>This document does not concern us</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>99E40134-61ED-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>Institution code is incorrect. Please provide correct institution code.</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>2F28DA6A-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>03</value>
						<definition>Unable to identify the person from the information provided. Please check.</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>3028DA6A-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>04</value>
						<definition>Entitlement document is unknown or not found. Please provide copy.</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>5D27AE76-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>05</value>
						<definition>Scheduled treatment may be suspected. Please check.</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>5E27AE76-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>06</value>
						<definition>There is an overlapping in hospitalisation periods. Please adjust the claim.</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B3508E7E-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>07</value>
						<definition>Person was not insured during benefits period. Please provide copy of entitlement document.</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B4508E7E-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>08</value>
						<definition>The period of benefits in kind is not covered by the entitlement period</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>178919AB-64ED-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>09</value>
						<definition>The period of benefits in kind is partially covered by the entitlement period. Please adjust the claim.</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>398C3186-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>10</value>
						<definition>The costs are to be settled by lump-sum as from [date should be filled in].</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>6B2E3BED-64ED-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>11</value>
						<definition>The costs are to be settled by lump-sum until [date should be filled in].</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>3A8C3186-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>12</value>
						<definition>The person is not registered on the entitlement document</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>17292390-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>13</value>
						<definition>The entitlement document has not been registered.</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>18292390-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>14</value>
						<definition>Double invoice [duplicated invoice number should be filled in]</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>91EA7D97-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>15</value>
						<definition>The entitlement in the state of residence started on [date should be filled in].</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>D4B1D09F-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>16</value>
						<definition>The benefits seem to concern an accident at work that happened on [date should be filled in].</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>E2677DA7-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>17</value>
						<definition>The person died on [date should be filled in]</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>947729AF-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>18</value>
						<definition>Lack of information about the other benefits provided. Please specify</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>957729AF-A349-E611-80CA-000D3A22E8CD</ccts:UniqueID>
						<value>19</value>
						<definition>Total amount of claim different to the sum of individual claims</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>44A2D5B7-B4BB-E611-80D2-000D3A22E8CD</ccts:UniqueID>
						<value>20</value>
						<definition>Total amount of individual claim different to the sum of benefits</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>17B3DCD1-B4BB-E611-80D2-000D3A22E8CD</ccts:UniqueID>
						<value>21</value>
						<definition>Cost of benefits have been refunded in full or partially to the insured person</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>6D5552E6-B4BB-E611-80D2-000D3A22E8CD</ccts:UniqueID>
						<value>22</value>
						<definition>Claim introduced after deadline [date should be filled in]</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>6231E6FD-B4BB-E611-80D2-000D3A22E8CD</ccts:UniqueID>
						<value>23</value>
						<definition>Contestation reply received after deadline [date should be filled in].</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>357D81BF-D0B7-EB11-80E7-000D3A22E8CD</ccts:UniqueID>
						<value>24</value>
						<definition>Entitlement ended [date should be filled in]</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>7E4A58C8-D0B7-EB11-80E7-000D3A22E8CD</ccts:UniqueID>
						<value>25</value>
						<definition>The person receives a dominating pension from another state</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>58BDA3CF-D0B7-EB11-80E7-000D3A22E8CD</ccts:UniqueID>
						<value>26</value>
						<definition>Details provided are inconsistent with the nature of benefits</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BA818C92-67ED-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>99</value>
						<definition>Other</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|99){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ContestationRefusalDateType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>402F6B80-A6EE-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'contestationRefusalCodeInfoDate' minOccurs='0' maxOccurs='1' type='sedS082:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>6F2F6B80-A6EE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIVeryLongStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A859AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='500' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='OtherRefusalCodeType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>74411697-5DED-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'contestationRefusalCodeInfoOther' minOccurs='0' maxOccurs='1' type='sedS082:EESSIVeryLongStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>76411697-5DED-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ContestationRefusalCodeInformationOnDuplicatedInvoiceType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>3A46E649-0449-E611-80C9-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'duplicatedTotalCLACreditorLiaisonBody' minOccurs='0' maxOccurs='1' type='sedS082:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>4046E649-0449-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'duplicatedCLANumberCreditorLiaisonBody' minOccurs='0' maxOccurs='1' type='sedS082:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>4146E649-0449-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ConditionalInformationDuplicatedInvoiceType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>E15B4F6F-522A-E711-80D4-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'ContestationRefusalCodeInformationOnDuplicated' minOccurs='0' maxOccurs='1' type='sedS082:ContestationRefusalCodeInformationOnDuplicatedInvoiceType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>E25B4F6F-522A-E711-80D4-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='IndividualClaimContestationType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>FB9C44F7-F748-E611-80C9-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'IDCreditorInstitution' minOccurs='1' maxOccurs='1' type='sedS082:EESSIInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>6083EC2F-F948-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'IDDebtorInstitution' minOccurs='1' maxOccurs='1' type='sedS082:EESSIInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>5F83EC2F-F948-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'References' minOccurs='1' maxOccurs='1' type='sedS082:ReferencesType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>7B411697-5DED-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'PersonReceivingBenefits' minOccurs='1' maxOccurs='1' type='sedS082:EESSIPersonInfoType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>D99C9CC4-0949-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'contestationRefusalCode' minOccurs='1' maxOccurs='1' type='sedS082:SicknessContestationRefusalCodeType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3D46E649-0449-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice>
				<xsd:element name = 'PleaseFillInIfContestationRefusalCode' minOccurs='0' maxOccurs='1' type='sedS082:ContestationRefusalDateType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>7A2F6B80-A6EE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name = 'PleaseFillInFollowingIfContestationRefusalCode' minOccurs='0' maxOccurs='1' type='sedS082:OtherRefusalCodeType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>7C411697-5DED-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name = 'ContestationRefusalCodeInformationOnDuplicated' minOccurs='0' maxOccurs='1' type='sedS082:ConditionalInformationDuplicatedInvoiceType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>4346E649-0449-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<xsd:element name = 'IndividualAmountContestation' minOccurs='1' maxOccurs='1' type='sedS082:EESSIPaymentEUType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>4246E649-0449-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='IndividualClaimContestationsType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A209C818-A549-E611-80CA-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'IndividualCOC' minOccurs='1' maxOccurs='unbounded' type='sedS082:IndividualClaimContestationType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>A509C818-A549-E611-80CA-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='S082'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>4DFCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SED</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>SED S082</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'GlobalNoteCOC' minOccurs='1' maxOccurs='1' type='sedS082:GlobalNoteClaimContestationType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>433C48B8-9418-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'IndividualCOCs' minOccurs='1' maxOccurs='1' type='sedS082:IndividualClaimContestationsType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>443C48B8-9418-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:unique name="S082individualCLANumberCreditorLiaisonBodyUniqueConstraint1">
					<xsd:selector xpath="IndividualCOC/References"/>
					<xsd:field xpath="individualCLANumberCreditorLiaisonBody"/>
				</xsd:unique>
				<xsd:unique name="S082individualCOCNumberDebtorLiaisonBodyUniqueConstraint2">
					<xsd:selector xpath="IndividualCOC/References"/>
					<xsd:field xpath="individualCOCNumberDebtorLiaisonBody"/>
				</xsd:unique>
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="1" ref="ds:Signature"/>
		</xsd:sequence>
		<xsd:attribute name='sedPackage' type='xsd:string' />
		<xsd:attribute name='sedGVer' type='xsd:int' />
		<xsd:attribute name='sedVer' type='xsd:int' />
	</xsd:complexType>
	<xsd:element name='S082' type='sedS082:S082'>
		<xsd:key name = 'sedS082keyname1'>
			<xsd:selector xpath = 'GlobalNoteCOC' />
			<xsd:field xpath = 'globalCLAReferenceCreditorLiaisonBody' />
		</xsd:key>
		<xsd:key name = 'sedS082keyname2'>
			<xsd:selector xpath = 'GlobalNoteCOC' />
			<xsd:field xpath = 'globalCOCReferenceDebtorLiaisonBody' />
		</xsd:key>
		<xsd:keyref name = 'sedS082keyrefname1' refer='sedS082:sedS082keyname1'>
			<xsd:selector xpath = 'IndividualCOCs/IndividualCOC/References' />
			<xsd:field xpath = 'globalCLAReferenceCreditorLiaisonBody' />
		</xsd:keyref>
		<xsd:keyref name = 'sedS082keyrefname2' refer='sedS082:sedS082keyname2'>
			<xsd:selector xpath = 'IndividualCOCs/IndividualCOC/References' />
			<xsd:field xpath = 'globalCOCReferenceDebtorLiaisonBody' />
		</xsd:keyref>
	</xsd:element>
</xsd:schema>