<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sedU023="http://ec.europa.eu/eessi/ns/4_4/U023" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" elementFormDefault="unqualified" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" targetNamespace="http://ec.europa.eu/eessi/ns/4_4/U023" version="4.4.0">
	<xsd:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="XAdES.xsd" />
	<xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xsd:complexType name='EESSIEUEFTACountryType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>927727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>A67727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>AT</value>
						<definition>Austria</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>937727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>BE</value>
						<definition>Belgium</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>947727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>BG</value>
						<definition>Bulgaria</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9D7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HR</value>
						<definition>Croatia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9F7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CY</value>
						<definition>Cyprus</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>957727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CZ</value>
						<definition>Czechia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>967727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>DK</value>
						<definition>Denmark</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>987727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>EE</value>
						<definition>Estonia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AC7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>FI</value>
						<definition>Finland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9C7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>FR</value>
						<definition>France</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>977727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>DE</value>
						<definition>Germany</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9A7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>EL</value>
						<definition>Greece</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A37727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HU</value>
						<definition>Hungary</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AF7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>IS</value>
						<definition>Iceland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>997727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>IE</value>
						<definition>Ireland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9E7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>IT</value>
						<definition>Italy</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A07727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>LV</value>
						<definition>Latvia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B07727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>LI</value>
						<definition>Liechtenstein</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A17727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>LT</value>
						<definition>Lithuania</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A27727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>LU</value>
						<definition>Luxembourg</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A47727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>MT</value>
						<definition>Malta</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A57727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>NL</value>
						<definition>Netherlands</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B17727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>NO</value>
						<definition>Norway</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A77727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>PL</value>
						<definition>Poland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A87727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>PT</value>
						<definition>Portugal</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A97727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>RO</value>
						<definition>Romania</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AB7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>SK</value>
						<definition>Slovakia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AA7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>SI</value>
						<definition>Slovenia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9B7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>ES</value>
						<definition>Spain</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AD7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>SE</value>
						<definition>Sweden</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B27727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CH</value>
						<definition>Switzerland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AE7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>UK</value>
						<definition>United Kingdom</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(AT|BE|BG|HR|CY|CZ|DK|EE|FI|FR|DE|EL|HU|IS|IE|IT|LV|LI|LT|LU|MT|NL|NO|PL|PT|RO|SK|SI|ES|SE|CH|UK){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIShortStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='65' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIInstitutionIDType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B659AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:pattern value='(AT|BE|BG|HR|CY|CZ|DK|EE|FI|FR|DE|EL|HU|IS|IE|IT|LV|LI|LT|LU|MT|NL|NO|PL|PT|RO|SK|SI|ES|SE|CH|UK|EU):[a-zA-Z0-9]{4,10}' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIMediumStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A659AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='155' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSIInstitutionType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2E243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'institutionID' minOccurs='1' maxOccurs='1' type='sedU023:EESSIInstitutionIDType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>38684F61-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'institutionName' minOccurs='1' maxOccurs='1' type='sedU023:EESSIMediumStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2AAB0BC6-ACFA-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSILocalCaseNumberType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>C764DE24-529C-E611-80D1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'country' minOccurs='1' maxOccurs='1' type='sedU023:EESSIEUEFTACountryType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>CD64DE24-529C-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'caseNumber' minOccurs='1' maxOccurs='1' type='sedU023:EESSIShortStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>6A970F32-539C-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'Institution' minOccurs='0' maxOccurs='1' type='sedU023:EESSIInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>6C970F32-539C-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSILocalCaseNumbersType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>C664DE24-529C-E611-80D1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'LocalCaseNumber' minOccurs='0' maxOccurs='unbounded' type='sedU023:EESSILocalCaseNumberType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>D064DE24-529C-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIReimbursementIDType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>BA59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSICRUniqueidentifierType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='GeneralInformationType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>7D02E557-3B8A-E611-80D0-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'reimbursementRequestID' minOccurs='1' maxOccurs='1' type='sedU023:EESSIReimbursementIDType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>8002E557-3B8A-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'reimbursementContestationID' minOccurs='1' maxOccurs='1' type='sedU023:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>8102E557-3B8A-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSICRIntegerIDType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B259AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:int'>
				<xsd:pattern value='[1-9]{1}[0-9]{0,15}' />
				<xsd:minInclusive value='1' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIPersonNameType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B059AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='155' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIDateOfBirthType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B159AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:date'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSISexType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>4E0A4E7A-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>4F0A4E7A-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>Male</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>CAA1E7BA-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>Female</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>D797EEC3-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>98</value>
						<definition>Unknown</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|98){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIPersonValidationType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2AD172C9-7289-E611-80D0-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'familyName' minOccurs='1' maxOccurs='1' type='sedU023:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3AD172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'forename' minOccurs='1' maxOccurs='1' type='sedU023:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3BD172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'dateBirth' minOccurs='1' maxOccurs='1' type='sedU023:EESSIDateOfBirthType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3CD172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'sex' minOccurs='1' maxOccurs='1' type='sedU023:EESSISexType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>379E16FD-8890-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ReasonForNonAcceptanceLateClaimMultipleType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>993EEFD4-D3F4-E511-80C1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>9A3EEFD4-D3F4-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>Submitted after time limit</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>7DB8FAE5-D3F4-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>No period recognised</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>13C326EE-D3F4-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>99</value>
						<definition>Other reason or additional information</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='unbounded'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|99){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIVeryLongStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A859AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='500' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='OtherReasonNonAcceptanceLateClaimType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>97243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'informationAboutOtherReasonOrAdditionalInformation' minOccurs='0' maxOccurs='1' type='sedU023:EESSIVeryLongStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>7AA0DFE0-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='NonAcceptanceIndividualClaimType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AA243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'reasonForNonAcceptance' minOccurs='1' maxOccurs='1' type='sedU023:ReasonForNonAcceptanceLateClaimMultipleType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>E5B34182-5290-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:unique name="sedU023UniqueConstraint1">
					<xsd:selector xpath="value"/>
					<xsd:field xpath="."/>
				</xsd:unique>
			</xsd:element>
			<xsd:element name = 'FillInIfReasonForNonAcceptance' minOccurs='0' maxOccurs='1' type='sedU023:OtherReasonNonAcceptanceLateClaimType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>B8B5818B-9518-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ReasonForPartialNonAcceptanceMultipleType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>06B8AF1D-C4C5-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>B772083D-C4C5-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>Partial acceptance due to ceiling under national law</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AA7D3446-C4C5-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>Period not justified</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>CF95B550-C4C5-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>03</value>
						<definition>Reimbursement claim incomplete</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>5914B360-C4C5-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>99</value>
						<definition>Other reason or additional information</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='unbounded'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|03|99){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIAmountType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B759AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:double'>
				<xsd:pattern value='(([1-9][0-9]{0,9})(\.\d{2,2})?|([0]{1})(\.\d{2,2})?)' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSIEUEFTACurrencyType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AF3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>B03712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>EUR</value>
						<definition>Euro</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B13712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>BGN</value>
						<definition>Bulgarian Lev</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B23712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CZK</value>
						<definition>Czech Koruna</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B33712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>DKK</value>
						<definition>Danish Krone</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B43712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>GBP</value>
						<definition>British Pound</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B53712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HRK</value>
						<definition>Croatian Kuna</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B63712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HUF</value>
						<definition>Hungarian Forint</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B73712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>PLN</value>
						<definition>Polish Zloty</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B83712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>RON</value>
						<definition>Romanian New Leu</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B93712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>SEK</value>
						<definition>Swedish Krona</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BA3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CHF</value>
						<definition>Swiss Franc</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BB3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>ISK</value>
						<definition>Icelandic Krona</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BC3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>NOK</value>
						<definition>Norwegian Krone</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>12090942-FAAC-E711-80DB-000D3A22E8CD</ccts:UniqueID>
						<value>LTL</value>
						<definition>Lithuanian Litas</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>13090942-FAAC-E711-80DB-000D3A22E8CD</ccts:UniqueID>
						<value>LVL</value>
						<definition>Latvian Lats</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(EUR|BGN|CZK|DKK|GBP|HRK|HUF|PLN|RON|SEK|CHF|ISK|NOK|LTL|LVL){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIPaymentEUType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>98393937-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'amount' minOccurs='1' maxOccurs='1' type='sedU023:EESSIAmountType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2A3E7DCE-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'currency' minOccurs='1' maxOccurs='1' type='sedU023:EESSIEUEFTACurrencyType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2B3E7DCE-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='PartialAcceptanceType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A2393937-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'AmountIntendedReimbursed' minOccurs='1' maxOccurs='1' type='sedU023:EESSIPaymentEUType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>43D172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSILongStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A759AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='255' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='ReimbursementIncompleteType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A6393937-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'informationMissingData' minOccurs='0' maxOccurs='1' type='sedU023:EESSILongStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>7F8C07E7-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='AdditionalInformationType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>1C3B5EFC-B4C3-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'additionalInformation' minOccurs='0' maxOccurs='1' type='sedU023:EESSIVeryLongStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>1E3B5EFC-B4C3-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='PartialAcceptanceIndividualClaimType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A1393937-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'reasonForPartialNonAcceptance' minOccurs='1' maxOccurs='1' type='sedU023:ReasonForPartialNonAcceptanceMultipleType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>1D3B5EFC-B4C3-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:unique name="sedU023UniqueConstraint2">
					<xsd:selector xpath="value"/>
					<xsd:field xpath="."/>
				</xsd:unique>
			</xsd:element>
			<xsd:element name = 'PartialAcceptanceDueCeiling' minOccurs='0' maxOccurs='1' type='sedU023:PartialAcceptanceType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>BBB5818B-9518-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'PartialNonAcceptanceReimbursementIncomplete' minOccurs='0' maxOccurs='1' type='sedU023:ReimbursementIncompleteType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>BEB5818B-9518-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'PartialNonAcceptanceOtherReason' minOccurs='0' maxOccurs='1' type='sedU023:AdditionalInformationType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>BFB5818B-9518-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ContestationType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>8B10452D-8E09-E711-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:choice>
				<xsd:element name = 'NonAcceptanceIndividualClaim' minOccurs='1' maxOccurs='1' type='sedU023:NonAcceptanceIndividualClaimType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>BAB5818B-9518-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name = 'PartialAcceptanceIndividualClaim' minOccurs='1' maxOccurs='1' type='sedU023:PartialAcceptanceIndividualClaimType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>BCB5818B-9518-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='IndividualClaimContestedType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A9243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'reimbursementRequestID' minOccurs='1' maxOccurs='1' type='sedU023:EESSIReimbursementIDType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>77A0DFE0-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'reimbursementContestationID' minOccurs='1' maxOccurs='1' type='sedU023:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>37D172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'sequentialNumberIndividualClaim' minOccurs='1' maxOccurs='1' type='sedU023:EESSICRIntegerIDType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>38D172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'contestedIndividualClaimID' minOccurs='1' maxOccurs='1' type='sedU023:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>39D172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'Person' minOccurs='1' maxOccurs='1' type='sedU023:EESSIPersonValidationType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3B08231E-FF78-E611-80CF-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'ContestationType' minOccurs='1' maxOccurs='1' type='sedU023:ContestationType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>8D10452D-8E09-E711-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='IndividualClaimsContestedType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B6C7E767-C079-E611-80CF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'IndividualClaimContested' minOccurs='1' maxOccurs='unbounded' type='sedU023:IndividualClaimContestedType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2B317E30-D978-E611-80CF-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='U023'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>83FCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SED</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>SED U023</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'LocalCaseNumbers' minOccurs='0' maxOccurs='1' type='sedU023:EESSILocalCaseNumbersType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>8E10452D-8E09-E711-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'GeneralInformation' minOccurs='1' maxOccurs='1' type='sedU023:GeneralInformationType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>490FCBAB-9418-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'IndividualClaimsContested' minOccurs='1' maxOccurs='1' type='sedU023:IndividualClaimsContestedType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>D0CBE291-9518-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:unique name="U023sequentialNumberIndividualClaimUniqueConstraint3">
					<xsd:selector xpath="IndividualClaimContested"/>
					<xsd:field xpath="sequentialNumberIndividualClaim"/>
				</xsd:unique>
				<xsd:unique name="U023contestedIndividualClaimIDUniqueConstraint4">
					<xsd:selector xpath="IndividualClaimContested"/>
					<xsd:field xpath="contestedIndividualClaimID"/>
				</xsd:unique>
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="1" ref="ds:Signature"/>
		</xsd:sequence>
		<xsd:attribute name='sedPackage' type='xsd:string' />
		<xsd:attribute name='sedGVer' type='xsd:int' />
		<xsd:attribute name='sedVer' type='xsd:int' />
	</xsd:complexType>
	<xsd:element name='U023' type='sedU023:U023'>
		<xsd:key name = 'sedU023keyname1'>
			<xsd:selector xpath = 'GeneralInformation' />
			<xsd:field xpath = 'reimbursementRequestID' />
		</xsd:key>
		<xsd:key name = 'sedU023keyname2'>
			<xsd:selector xpath = 'GeneralInformation' />
			<xsd:field xpath = 'reimbursementContestationID' />
		</xsd:key>
		<xsd:keyref name = 'sedU023keyrefname1' refer='sedU023:sedU023keyname1'>
			<xsd:selector xpath = 'IndividualClaimsContested/IndividualClaimContested' />
			<xsd:field xpath = 'reimbursementRequestID' />
		</xsd:keyref>
		<xsd:keyref name = 'sedU023keyrefname2' refer='sedU023:sedU023keyname2'>
			<xsd:selector xpath = 'IndividualClaimsContested/IndividualClaimContested' />
			<xsd:field xpath = 'reimbursementContestationID' />
		</xsd:keyref>
	</xsd:element>
</xsd:schema>