<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sedS011="http://ec.europa.eu/eessi/ns/4_4/S011" xmlns:CC="http://ec.europa.eu/eessi/ns/4_4/CC"	xmlns:SSec="http://ec.europa.eu/eessi/ns/4_4/SSec" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" elementFormDefault="unqualified" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" targetNamespace="http://ec.europa.eu/eessi/ns/4_4/S011" version="4.4.0">
<xsd:import namespace="http://ec.europa.eu/eessi/ns/4_4/SSec" schemaLocation="SSec-4.4.xsd"/>
<xsd:import namespace="http://ec.europa.eu/eessi/ns/4_4/CC" schemaLocation="CC-4.4.xsd"/>
	<xsd:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="XAdES.xsd" />
	<xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xsd:complexType name='InstitutionPlaceStayType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>57313DE1-9179-E611-80CF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'country' minOccurs='0' maxOccurs='1' type='CC:EESSIEUEFTACountryType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>58313DE1-9179-E611-80CF-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'Institution' minOccurs='0' maxOccurs='1' type='CC:EESSIInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>59313DE1-9179-E611-80CF-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='AttachedMedicalAuthorisationOtherType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>29C5ADB7-0624-E611-80C8-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>B8E8B7D4-0624-E611-80C8-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>Medical report is attached</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>18A24AE1-0624-E611-80C8-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>authorisation is attached</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>E1CEF0E9-0624-E611-80C8-000D3A22E8CD</ccts:UniqueID>
						<value>99</value>
						<definition>Other</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|99){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='AttachmentsType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AAB6A7B9-6A2D-E611-80C8-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'attachments' minOccurs='0' maxOccurs='1' type='sedS011:AttachedMedicalAuthorisationOtherType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>ABB6A7B9-6A2D-E611-80C8-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'otherAttachments' minOccurs='0' maxOccurs='1' type='CC:EESSILongStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>002A3D52-0AFD-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='AttachmentType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>86F0E6D9-DCBB-E611-80D2-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'Attachment' minOccurs='0' maxOccurs='unbounded' type='sedS011:AttachmentsType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>88F0E6D9-DCBB-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='S011'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>1AFCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SED</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>SED S011</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'Person' minOccurs='1' maxOccurs='1' type='SSec:SPersonFullInfoType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>56ED0310-9618-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'PersonAddress' minOccurs='0' maxOccurs='1' type='CC:EESSIAddressWorldType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>5BED0310-9618-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'InstitutionPlaceStay' minOccurs='0' maxOccurs='1' type='sedS011:InstitutionPlaceStayType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>5CED0310-9618-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'StartingEndingDateEntitlement' minOccurs='1' maxOccurs='1' type='CC:EESSIPeriodType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>C25A2216-9618-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'Attachments' minOccurs='0' maxOccurs='1' type='sedS011:AttachmentType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>C35A2216-9618-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'Treatment' minOccurs='1' maxOccurs='1' type='SSec:STreatmentType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>ADB6A7B9-6A2D-E611-80C8-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="1" ref="ds:Signature"/>
		</xsd:sequence>
		<xsd:attribute name='sedPackage' type='xsd:string' />
		<xsd:attribute name='sedGVer' type='xsd:int' />
		<xsd:attribute name='sedVer' type='xsd:int' />
	</xsd:complexType>
	<xsd:element name='S011' type='sedS011:S011' />
</xsd:schema>