<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sedS048="http://ec.europa.eu/eessi/ns/4_4/S048" xmlns:CC="http://ec.europa.eu/eessi/ns/4_4/CC"	xmlns:SSec="http://ec.europa.eu/eessi/ns/4_4/SSec" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" elementFormDefault="unqualified" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" targetNamespace="http://ec.europa.eu/eessi/ns/4_4/S048" version="4.4.0">
<xsd:import namespace="http://ec.europa.eu/eessi/ns/4_4/SSec" schemaLocation="SSec-4.4.xsd"/>
<xsd:import namespace="http://ec.europa.eu/eessi/ns/4_4/CC" schemaLocation="CC-4.4.xsd"/>
	<xsd:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="XAdES.xsd" />
	<xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xsd:complexType name='InformationTypeS048MultipleType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>85BC045E-AFDC-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>8D331EAD-B5DC-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>The last day of incapacity for work of the person concerned</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>8E331EAD-B5DC-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>Crucial information or any other additional information</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='unbounded'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='LastDayIncapacityForWorkType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>718CE717-B2DC-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'theLastDayIncapacityForWorkPersonConcerned' minOccurs='0' maxOccurs='1' type='CC:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>738CE717-B2DC-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='WeInformAboutType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>42343C49-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'typeInformation' minOccurs='0' maxOccurs='1' type='sedS048:InformationTypeS048MultipleType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>728CE717-B2DC-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:unique name="sedS048UniqueConstraint1">
					<xsd:selector xpath="value"/>
					<xsd:field xpath="."/>
				</xsd:unique>
			</xsd:element>
			<xsd:element name = 'TheLastDayIncapacityForWorkPersonConcerned' minOccurs='0' maxOccurs='1' type='sedS048:LastDayIncapacityForWorkType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>748CE717-B2DC-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'OtherCrucialInformation' minOccurs='0' maxOccurs='1' type='SSec:SOtherCrucialInformationType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>5D2F3187-A529-E711-80D4-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='IssuedDocumentType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>89BB383D-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'document' minOccurs='1' maxOccurs='1' type='CC:EESSITinyStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>52C558FF-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='S048'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>34FCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SED</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>SED S048</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'Person' minOccurs='1' maxOccurs='1' type='SSec:SPersonFullInfoType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2A9387E0-9618-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'PersonAddress' minOccurs='0' maxOccurs='1' type='CC:EESSIAddressWorldType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>299387E0-9618-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'WeInformAbout' minOccurs='1' maxOccurs='1' type='sedS048:WeInformAboutType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>71D566DA-9618-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'Attachments' minOccurs='0' maxOccurs='1' type='sedS048:IssuedDocumentType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>70D566DA-9618-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="1" ref="ds:Signature"/>
		</xsd:sequence>
		<xsd:attribute name='sedPackage' type='xsd:string' />
		<xsd:attribute name='sedGVer' type='xsd:int' />
		<xsd:attribute name='sedVer' type='xsd:int' />
	</xsd:complexType>
	<xsd:element name='S048' type='sedS048:S048' />
</xsd:schema>