<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sedS115="http://ec.europa.eu/eessi/ns/4_4/S115" xmlns:CC="http://ec.europa.eu/eessi/ns/4_4/CC"	xmlns:SSec="http://ec.europa.eu/eessi/ns/4_4/SSec" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" elementFormDefault="unqualified" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" targetNamespace="http://ec.europa.eu/eessi/ns/4_4/S115" version="4.4.0">
<xsd:import namespace="http://ec.europa.eu/eessi/ns/4_4/SSec" schemaLocation="SSec-4.4.xsd"/>
<xsd:import namespace="http://ec.europa.eu/eessi/ns/4_4/CC" schemaLocation="CC-4.4.xsd"/>
	<xsd:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="XAdES.xsd" />
	<xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xsd:complexType name='MonthsInventoryDownPaymentInformationReplyType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>E2199469-849F-E611-80D1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'globalIMOReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='CC:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>EA199469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalCLAIMOReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='CC:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>EB199469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalIDPIMOReferenceDebtorLiaisonBody' minOccurs='1' maxOccurs='1' type='CC:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>EC199469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalRPYIDPIMOReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='CC:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>ED199469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'TotalClaimAmount' minOccurs='1' maxOccurs='1' type='CC:EESSIPaymentEUType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>131A9469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'DownPaymentAmount' minOccurs='1' maxOccurs='1' type='CC:EESSIPaymentEUType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>9B67EDA7-852A-E711-80D4-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'downPaymentPercentage' minOccurs='1' maxOccurs='1' type='CC:EESSIPercentageType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>4F6648BE-564F-E711-80D5-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'BankAccount' minOccurs='1' maxOccurs='1' type='CC:EESSISEPABankDetailsType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>171A9469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'replyCode' minOccurs='1' maxOccurs='1' type='CC:EESSIDownPaymentRefusalCodeType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>FB199469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'dateSubmission' minOccurs='1' maxOccurs='1' type='CC:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>FC199469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='S115'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>66FCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SED</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>SED S115</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'GlobalNoteRPYIDPIMO' minOccurs='1' maxOccurs='1' type='sedS115:MonthsInventoryDownPaymentInformationReplyType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>161A9469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="1" ref="ds:Signature"/>
		</xsd:sequence>
		<xsd:attribute name='sedPackage' type='xsd:string' />
		<xsd:attribute name='sedGVer' type='xsd:int' />
		<xsd:attribute name='sedVer' type='xsd:int' />
	</xsd:complexType>
	<xsd:element name='S115' type='sedS115:S115' />
</xsd:schema>