<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sedS104="http://ec.europa.eu/eessi/ns/4_4/S104" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" elementFormDefault="unqualified" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" targetNamespace="http://ec.europa.eu/eessi/ns/4_4/S104" version="4.4.0">
	<xsd:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="XAdES.xsd" />
	<xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xsd:simpleType name='EESSICRUniqueidentifierType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSICRIndividualClaimsCountType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AB59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:int'>
				<xsd:minInclusive value='0' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIBusinessDateType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:date'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='GlobalNoteMonthsInventoryContestationReplyType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>C5F70CDA-F5A1-E611-A960-00155D00FE00</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'globalIMOReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>EAF70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalCOCIMOReferenceDebtorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>EBF70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalRPYCOCIMOCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>ECF70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'totalNumberReplyContestations' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRIndividualClaimsCountType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>758861B7-57FE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'totalNumberAcceptedMonthsContested' minOccurs='1' maxOccurs='1' type='xsd:int'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>748861B7-57FE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'dateSubmission' minOccurs='1' maxOccurs='1' type='sedS104:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>F1F70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIInstitutionIDType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B659AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:pattern value='(AT|BE|BG|HR|CY|CZ|DK|EE|FI|FR|DE|EL|HU|IS|IE|IT|LV|LI|LT|LU|MT|NL|NO|PL|PT|RO|SK|SI|ES|SE|CH|UK|EU):[a-zA-Z0-9]{4,10}' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIMediumStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A659AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='155' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSIInstitutionType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2E243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'institutionID' minOccurs='1' maxOccurs='1' type='sedS104:EESSIInstitutionIDType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>38684F61-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'institutionName' minOccurs='1' maxOccurs='1' type='sedS104:EESSIMediumStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2AAB0BC6-ACFA-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ReferencesType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>C7F70CDA-F5A1-E611-A960-00155D00FE00</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'globalIMOReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>F7F70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalCOCIMOReferenceDebtorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>F8F70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalRPYCOCIMOReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>F9F70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'individualIMONumberCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>FAF70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'individualCOCIMONumberDebtorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>FBF70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'individualRPYCOCIMONumberCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS104:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>FCF70CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIPersonNameType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B059AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='155' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIDateOfBirthType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B159AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:date'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSISexType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>4E0A4E7A-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>4F0A4E7A-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>Male</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>CAA1E7BA-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>Female</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>D797EEC3-00F1-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>98</value>
						<definition>Unknown</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|98){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIPersonValidationType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2AD172C9-7289-E611-80D0-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'familyName' minOccurs='1' maxOccurs='1' type='sedS104:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3AD172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'forename' minOccurs='1' maxOccurs='1' type='sedS104:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3BD172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'dateBirth' minOccurs='1' maxOccurs='1' type='sedS104:EESSIDateOfBirthType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3CD172C9-7289-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'sex' minOccurs='1' maxOccurs='1' type='sedS104:EESSISexType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>379E16FD-8890-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIPINType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AE59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='65' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSIPersonIdentificationNumberType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>91BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'pINPersonInCompetentMemberState' minOccurs='1' maxOccurs='1' type='sedS104:EESSIPINType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>9ABF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'pINPersonInMemberStateStayOrResidence' minOccurs='0' maxOccurs='1' type='sedS104:EESSIPINType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>9BBF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIPersonInfoType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>94BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'PersonInformation' minOccurs='1' maxOccurs='1' type='sedS104:EESSIPersonValidationType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>A3BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'familyNameAtBirth' minOccurs='0' maxOccurs='1' type='sedS104:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>97BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'forenameAtBirth' minOccurs='0' maxOccurs='1' type='sedS104:EESSIPersonNameType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>98BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'PersonIdentificationNumber' minOccurs='1' maxOccurs='1' type='sedS104:EESSIPersonIdentificationNumberType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>A4BF3EBC-09C2-E611-80D2-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ReplyCodeCOCIMOType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>7DB990EC-754F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>0BAB2D11-764F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>Contestation accepted - individual IMO concerned is totally withdrawn</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>186B6D29-764F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>Contestation accepted -  IMO concerned is decreased</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>E6E5FA41-764F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>03</value>
						<definition>Contestation after deadline, received on [date should be filled in]</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>43696E57-764F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>04</value>
						<definition>Information requested updated</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>320FEA65-764F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>05</value>
						<definition>After checking, no double invoice found</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>94FF5383-764F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>06</value>
						<definition>The primary entitlement in state of residence starts on [date should be filled in]</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>EBF461AD-764F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>07</value>
						<definition>The person receives a pension in his/her state of residence as from [date should be filled in], copy of the decision attached</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>7E3655D8-764F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>08</value>
						<definition>The person receives a dominating pension from another state, copy of pension decision attached</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>1FCF33EC-764F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>09</value>
						<definition>The family member is not entitled in the state of residence</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>8187C208-774F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>10</value>
						<definition>The costs are not to be settled by actual costs</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AF64091F-774F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>11</value>
						<definition>The family member is now registered on the entitlement document</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>6CA75035-774F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>12</value>
						<definition>According to the attached documents, the invoice has to be paid</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>63C99D45-774F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>13</value>
						<definition>Enclosed you find the entitlement documents</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>998B2655-774F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>14</value>
						<definition>Enclosed you find the requested documents</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BCD1E584-774F-E711-80D5-000D3A22E8CD</ccts:UniqueID>
						<value>99</value>
						<definition>Other [field 'Other' should be filled in]</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|03|04|05|06|07|08|09|10|11|12|13|14|99){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='SSicknessEntitlementDocumentCodeContentTypeLumpSumType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>893794BC-CFFD-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SC.Sickness.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>5DF236D2-CFFD-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>S1 - Registering for health care cover</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>5EF236D2-CFFD-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>S072 - Entitlement document - Residence</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>5DA9D7DA-CFFD-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>03</value>
						<definition>E109 - Certificate for the Registration of members of the employed or self-employed person's family</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>5EA9D7DA-CFFD-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>04</value>
						<definition>E121 - Certificate for the registration of pensioners</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|03|04){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSICompletedPeriodType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>36243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'startDate' minOccurs='1' maxOccurs='1' type='sedS104:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>D0B78E2B-774A-E611-80CA-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'endDate' minOccurs='1' maxOccurs='1' type='sedS104:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>34684F61-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIOpenPeriodType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>D65D19DB-4EF4-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>7F458BE8-4EF4-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>Open-Ended Period</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>80458BE8-4EF4-E611-80D3-000D3A22E8CD</ccts:UniqueID>
						<value>98</value>
						<definition>End date of the period is unknown</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|98){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIOngoingIntervalType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2A82CE51-F844-E611-80C9-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'typeOpenPeriod' minOccurs='1' maxOccurs='1' type='sedS104:EESSIOpenPeriodType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>A8FBFF38-4FF4-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'startDate' minOccurs='1' maxOccurs='1' type='sedS104:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3F82CE51-F844-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIOngoingPeriodType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2C243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:choice>
				<xsd:element name = 'FixedPeriod' minOccurs='1' maxOccurs='1' type='sedS104:EESSICompletedPeriodType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>E82A071E-00A2-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name = 'OpenPeriod' minOccurs='1' maxOccurs='1' type='sedS104:EESSIOngoingIntervalType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>E72A071E-00A2-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='UpdateEntitlementDocumentType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>6FBD3087-2BD3-EB11-80E7-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'entitlementDocument' minOccurs='1' maxOccurs='1' type='sedS104:SSicknessEntitlementDocumentCodeContentTypeLumpSumType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>71BD3087-2BD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'ValidityPeriod' minOccurs='1' maxOccurs='1' type='sedS104:EESSIOngoingPeriodType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>EA9684A5-56D3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIPeriodType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2582CE51-F844-E611-80C9-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'startDate' minOccurs='1' maxOccurs='1' type='sedS104:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3882CE51-F844-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'endDate' minOccurs='1' maxOccurs='1' type='sedS104:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3982CE51-F844-E611-80C9-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='UpdateDebtorInstitutionType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B84F52AF-5BD3-EB11-80E7-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'IDDebtorInstitution' minOccurs='1' maxOccurs='1' type='sedS104:EESSIInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>BB4F52AF-5BD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ContestationReplyCode0102Type'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>70BD3087-2BD3-EB11-80E7-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'numberMonthsAfterAcceptedContestation' minOccurs='0' maxOccurs='1' type='xsd:int'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>5F23EFE1-58D3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'UpdateEntitlementDocument' minOccurs='0' maxOccurs='1' type='sedS104:UpdateEntitlementDocumentType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>72BD3087-2BD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'UpdateAccountingPeriod' minOccurs='0' maxOccurs='1' type='sedS104:EESSIPeriodType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>B94F52AF-5BD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'UpdateDebtorInstitution' minOccurs='0' maxOccurs='1' type='sedS104:UpdateDebtorInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>BA4F52AF-5BD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'UpdatePersonReceivingBenefits' minOccurs='0' maxOccurs='1' type='sedS104:EESSIPersonInfoType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>00CBFEBE-5DD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EntitlementStartingDateType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>608861B7-57FE-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'contestationRefusalCodeInfoDate' minOccurs='0' maxOccurs='1' type='sedS104:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>29B1F820-834F-E711-80D5-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ContestationReplyCodeInformationRequestedType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>DB0F1D24-5FD3-EB11-80E7-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'UpdateEntitlementDocument' minOccurs='0' maxOccurs='1' type='sedS104:UpdateEntitlementDocumentType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>DD0F1D24-5FD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'UpdateAccountingPeriod' minOccurs='0' maxOccurs='1' type='sedS104:EESSIPeriodType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>DE0F1D24-5FD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'UpdateDebtorInstitution' minOccurs='0' maxOccurs='1' type='sedS104:UpdateDebtorInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>DF0F1D24-5FD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'UpdatePersonReceivingBenefits' minOccurs='0' maxOccurs='1' type='sedS104:EESSIPersonInfoType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>E00F1D24-5FD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIVeryLongStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A859AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='500' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='OtherReplyCodeType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>5E8861B7-57FE-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'contestationRefusalCodeInfoOther' minOccurs='0' maxOccurs='1' type='sedS104:EESSIVeryLongStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>26B1F820-834F-E711-80D5-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ReplyCodeType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>C9F70CDA-F5A1-E611-A960-00155D00FE00</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'replyCodeCOCIMO' minOccurs='1' maxOccurs='1' type='sedS104:ReplyCodeCOCIMOType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>28B1F820-834F-E711-80D5-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice>
				<xsd:element name = 'ConditionalAcceptance' minOccurs='0' maxOccurs='1' type='sedS104:ContestationReplyCode0102Type'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>3EA0AC76-54D3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name = 'ConditionalDate' minOccurs='0' maxOccurs='1' type='sedS104:EntitlementStartingDateType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>2AB1F820-834F-E711-80D5-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name = 'InformationRequested' minOccurs='0' maxOccurs='1' type='sedS104:ContestationReplyCodeInformationRequestedType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>59E78486-62D3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name = 'OtherContestationRefusalCode' minOccurs='0' maxOccurs='1' type='sedS104:OtherReplyCodeType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>2CB1F820-834F-E711-80D5-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='ContestedMonthsNumberType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>618861B7-57FE-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'numberMonthsAfterAcceptedContestation' minOccurs='1' maxOccurs='1' type='xsd:int'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>27B1F820-834F-E711-80D5-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='IndividualMonthsInventoryContestationReplyType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>C6F70CDA-F5A1-E611-A960-00155D00FE00</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'IDCreditorInstitution' minOccurs='1' maxOccurs='1' type='sedS104:EESSIInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>4DF80CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'IDDebtorInstitution' minOccurs='1' maxOccurs='1' type='sedS104:EESSIInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>4EF80CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'References' minOccurs='1' maxOccurs='1' type='sedS104:ReferencesType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>4BF80CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'PersonReceivingBenefits' minOccurs='1' maxOccurs='1' type='sedS104:EESSIPersonInfoType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>50F80CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'ReplyCode' minOccurs='1' maxOccurs='1' type='sedS104:ReplyCodeType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>55F80CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'NumberMonthsAfterAcceptedContestation' minOccurs='1' maxOccurs='1' type='sedS104:ContestedMonthsNumberType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>E10F1D24-5FD3-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='IndividualMonthsInventoryContestationRepliesType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>CBF70CDA-F5A1-E611-A960-00155D00FE00</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'IndividualRPYCOCIMO' minOccurs='1' maxOccurs='unbounded' type='sedS104:IndividualMonthsInventoryContestationReplyType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>57F80CDA-F5A1-E611-A960-00155D00FE00</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='S104'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>5CFCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SED</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>SED S104</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'GlobalNoteRPYCOCIMO' minOccurs='1' maxOccurs='1' type='sedS104:GlobalNoteMonthsInventoryContestationReplyType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>006B7725-9718-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'IndividualRPYCOCIMOs' minOccurs='1' maxOccurs='1' type='sedS104:IndividualMonthsInventoryContestationRepliesType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>C2CA130D-9818-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
				<xsd:unique name="S104individualIMONumberCreditorLiaisonBodyUniqueConstraint1">
					<xsd:selector xpath="IndividualRPYCOCIMO/References"/>
					<xsd:field xpath="individualIMONumberCreditorLiaisonBody"/>
				</xsd:unique>
				<xsd:unique name="S104individualCOCIMONumberDebtorLiaisonBodyUniqueConstraint2">
					<xsd:selector xpath="IndividualRPYCOCIMO/References"/>
					<xsd:field xpath="individualCOCIMONumberDebtorLiaisonBody"/>
				</xsd:unique>
				<xsd:unique name="S104individualRPYCOCIMONumberCreditorLiaisonBodyUniqueConstraint3">
					<xsd:selector xpath="IndividualRPYCOCIMO/References"/>
					<xsd:field xpath="individualRPYCOCIMONumberCreditorLiaisonBody"/>
				</xsd:unique>
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="1" ref="ds:Signature"/>
		</xsd:sequence>
		<xsd:attribute name='sedPackage' type='xsd:string' />
		<xsd:attribute name='sedGVer' type='xsd:int' />
		<xsd:attribute name='sedVer' type='xsd:int' />
	</xsd:complexType>
	<xsd:element name='S104' type='sedS104:S104'>
		<xsd:key name = 'sedS104keyname1'>
			<xsd:selector xpath = 'GlobalNoteRPYCOCIMO' />
			<xsd:field xpath = 'globalIMOReferenceCreditorLiaisonBody' />
		</xsd:key>
		<xsd:key name = 'sedS104keyname2'>
			<xsd:selector xpath = 'GlobalNoteRPYCOCIMO' />
			<xsd:field xpath = 'globalCOCIMOReferenceDebtorLiaisonBody' />
		</xsd:key>
		<xsd:key name = 'sedS104keyname3'>
			<xsd:selector xpath = 'GlobalNoteRPYCOCIMO' />
			<xsd:field xpath = 'globalRPYCOCIMOCreditorLiaisonBody' />
		</xsd:key>
		<xsd:keyref name = 'sedS104keyrefname1' refer='sedS104:sedS104keyname1'>
			<xsd:selector xpath = 'IndividualRPYCOCIMOs/IndividualRPYCOCIMO/References' />
			<xsd:field xpath = 'globalIMOReferenceCreditorLiaisonBody' />
		</xsd:keyref>
		<xsd:keyref name = 'sedS104keyrefname2' refer='sedS104:sedS104keyname2'>
			<xsd:selector xpath = 'IndividualRPYCOCIMOs/IndividualRPYCOCIMO/References' />
			<xsd:field xpath = 'globalCOCIMOReferenceDebtorLiaisonBody' />
		</xsd:keyref>
		<xsd:keyref name = 'sedS104keyrefname3' refer='sedS104:sedS104keyname3'>
			<xsd:selector xpath = 'IndividualRPYCOCIMOs/IndividualRPYCOCIMO/References' />
			<xsd:field xpath = 'globalRPYCOCIMOReferenceCreditorLiaisonBody' />
		</xsd:keyref>
	</xsd:element>
</xsd:schema>