<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sedS110="http://ec.europa.eu/eessi/ns/4_4/S110" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" elementFormDefault="unqualified" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" targetNamespace="http://ec.europa.eu/eessi/ns/4_4/S110" version="4.4.0">
	<xsd:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="XAdES.xsd" />
	<xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xsd:simpleType name='EESSICRUniqueidentifierType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B459AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIYearType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AC59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:int'>
				<xsd:pattern value='(18[5-9]\d|19\d\d|2[0|1]\d\d)' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='SLumpSumLegalCategoryType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>834515A4-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SC.Sickness.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>E064C8C5-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>IR 987/2009, Art 63, 2.a</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BF85DDD3-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>IR 987/2009, Art 63, 2.b</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>00D8B4DE-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID>
						<value>03</value>
						<definition>IR 574/72, Art. 94</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>CFEC90E9-709F-E611-80D1-000D3A22E8CD</ccts:UniqueID>
						<value>04</value>
						<definition>IR 574/72, Art. 95</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|03|04){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='SLumpSumCategoryType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>EEE959FF-4B26-E611-80C8-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SC.Sickness.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>62647B1F-4C26-E611-80C8-000D3A22E8CD</ccts:UniqueID>
						<value>01</value>
						<definition>IR 987/2009, Art 64, Age 0-19</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>5DA6F629-4C26-E611-80C8-000D3A22E8CD</ccts:UniqueID>
						<value>02</value>
						<definition>IR 987/2009, Art 64, Age 20-64</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>85E23636-4C26-E611-80C8-000D3A22E8CD</ccts:UniqueID>
						<value>03</value>
						<definition>IR 987/2009, Art 64, Age 65+</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(01|02|03){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='SLumpSumCategoryArt63P2aType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>91DB36B1-769F-E611-80D1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SC.Sickness</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'lumpSumCategory' minOccurs='0' maxOccurs='1' type='sedS110:SLumpSumCategoryType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>061A9469-849F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='SLumpSumCategoryArt63P2bType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>BA0DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SC.Sickness</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'lumpSumCategory' minOccurs='0' maxOccurs='1' type='sedS110:SLumpSumCategoryType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>BC0DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='SLumpSumLegalCategoryClassType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B90DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SC.Sickness</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'lumpSumCategoryBasedPersonStatus' minOccurs='1' maxOccurs='1' type='sedS110:SLumpSumLegalCategoryType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>BB0DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:choice>
				<xsd:element name = 'Art63p2a' minOccurs='0' maxOccurs='1' type='sedS110:SLumpSumCategoryArt63P2aType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>B2DB36B1-769F-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name = 'Art63p2b' minOccurs='0' maxOccurs='1' type='sedS110:SLumpSumCategoryArt63P2bType'>
					<xsd:annotation>
						<xsd:documentation xml:lang="en">
							<ccts:DictionaryEntryName>CF0DFC2F-EBEE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIAmountType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B759AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:double'>
				<xsd:pattern value='(([1-9][0-9]{0,9})(\.\d{2,2})?|([0]{1})(\.\d{2,2})?)' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSIEUEFTACurrencyType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AF3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>B03712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>EUR</value>
						<definition>Euro</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B13712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>BGN</value>
						<definition>Bulgarian Lev</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B23712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CZK</value>
						<definition>Czech Koruna</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B33712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>DKK</value>
						<definition>Danish Krone</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B43712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>GBP</value>
						<definition>British Pound</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B53712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HRK</value>
						<definition>Croatian Kuna</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B63712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HUF</value>
						<definition>Hungarian Forint</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B73712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>PLN</value>
						<definition>Polish Zloty</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B83712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>RON</value>
						<definition>Romanian New Leu</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B93712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>SEK</value>
						<definition>Swedish Krona</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BA3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CHF</value>
						<definition>Swiss Franc</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BB3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>ISK</value>
						<definition>Icelandic Krona</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>BC3712C1-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>NOK</value>
						<definition>Norwegian Krone</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>12090942-FAAC-E711-80DB-000D3A22E8CD</ccts:UniqueID>
						<value>LTL</value>
						<definition>Lithuanian Litas</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>13090942-FAAC-E711-80DB-000D3A22E8CD</ccts:UniqueID>
						<value>LVL</value>
						<definition>Latvian Lats</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(EUR|BGN|CZK|DKK|GBP|HRK|HUF|PLN|RON|SEK|CHF|ISK|NOK|LTL|LVL){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSIPaymentEUType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>98393937-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'amount' minOccurs='1' maxOccurs='1' type='sedS110:EESSIAmountType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2A3E7DCE-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'currency' minOccurs='1' maxOccurs='1' type='sedS110:EESSIEUEFTACurrencyType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2B3E7DCE-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIIBANType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A959AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:pattern value='[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{4}[a-zA-Z0-9]{7}([a-zA-Z0-9]?){0,16}' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIBICSWIFTType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>AA59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:pattern value='([a-zA-Z]){4}([a-zA-Z]){2}([0-9a-zA-Z]){2}([0-9a-zA-Z]{3})?' />
				<xsd:minLength value='1' />
				<xsd:maxLength value='11' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSISEPABankDetailsType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>19243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'IBAN' minOccurs='1' maxOccurs='1' type='sedS110:EESSIIBANType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>4665465B-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'BICSWIFT' minOccurs='0' maxOccurs='1' type='sedS110:EESSIBICSWIFTType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>4765465B-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIBusinessDateType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:date'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='ClaimForReimbursementFixedAmountsMonthsInventoryClaimType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>03E90168-6FA2-E611-80D1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'globalIMOReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS110:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>14E90168-6FA2-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'globalCLAIMOReferenceCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS110:EESSICRUniqueidentifierType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>15E90168-6FA2-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'financialYear' minOccurs='1' maxOccurs='1' type='sedS110:EESSIYearType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>07E90168-6FA2-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'LumpSumLegalCategory' minOccurs='1' maxOccurs='1' type='sedS110:SLumpSumLegalCategoryClassType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3123DFF5-92D2-EB11-80E7-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'LumpSum' minOccurs='1' maxOccurs='1' type='sedS110:EESSIPaymentEUType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>1CE90168-6FA2-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'totalNumberMonths' minOccurs='1' maxOccurs='1' type='xsd:int'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>6B8861B7-57FE-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'TotalAmountClaim' minOccurs='1' maxOccurs='1' type='sedS110:EESSIPaymentEUType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>596648BE-564F-E711-80D5-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'BankAccountCreditorLiaisonBody' minOccurs='1' maxOccurs='1' type='sedS110:EESSISEPABankDetailsType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>1DE90168-6FA2-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'dateSubmission' minOccurs='1' maxOccurs='1' type='sedS110:EESSIBusinessDateType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>09E90168-6FA2-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='S110'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>61FCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SED</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>SED S110</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'GlobalNoteCLAIMO' minOccurs='1' maxOccurs='1' type='sedS110:ClaimForReimbursementFixedAmountsMonthsInventoryClaimType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>1FE90168-6FA2-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="1" ref="ds:Signature"/>
		</xsd:sequence>
		<xsd:attribute name='sedPackage' type='xsd:string' />
		<xsd:attribute name='sedGVer' type='xsd:int' />
		<xsd:attribute name='sedVer' type='xsd:int' />
	</xsd:complexType>
	<xsd:element name='S110' type='sedS110:S110' />
</xsd:schema>