<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sedU021="http://ec.europa.eu/eessi/ns/4_4/U021" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" elementFormDefault="unqualified" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" targetNamespace="http://ec.europa.eu/eessi/ns/4_4/U021" version="4.4.0">
	<xsd:import namespace="http://uri.etsi.org/01903/v1.3.2#" schemaLocation="XAdES.xsd" />
	<xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xsd:complexType name='EESSIEUEFTACountryType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>927727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.ENUM</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					<CodeListEntry>
						<ccts:UniqueID>A67727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>AT</value>
						<definition>Austria</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>937727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>BE</value>
						<definition>Belgium</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>947727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>BG</value>
						<definition>Bulgaria</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9D7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HR</value>
						<definition>Croatia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9F7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CY</value>
						<definition>Cyprus</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>957727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CZ</value>
						<definition>Czechia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>967727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>DK</value>
						<definition>Denmark</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>987727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>EE</value>
						<definition>Estonia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AC7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>FI</value>
						<definition>Finland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9C7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>FR</value>
						<definition>France</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>977727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>DE</value>
						<definition>Germany</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9A7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>EL</value>
						<definition>Greece</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A37727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>HU</value>
						<definition>Hungary</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AF7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>IS</value>
						<definition>Iceland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>997727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>IE</value>
						<definition>Ireland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9E7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>IT</value>
						<definition>Italy</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A07727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>LV</value>
						<definition>Latvia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B07727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>LI</value>
						<definition>Liechtenstein</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A17727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>LT</value>
						<definition>Lithuania</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A27727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>LU</value>
						<definition>Luxembourg</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A47727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>MT</value>
						<definition>Malta</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A57727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>NL</value>
						<definition>Netherlands</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B17727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>NO</value>
						<definition>Norway</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A77727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>PL</value>
						<definition>Poland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A87727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>PT</value>
						<definition>Portugal</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>A97727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>RO</value>
						<definition>Romania</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AB7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>SK</value>
						<definition>Slovakia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AA7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>SI</value>
						<definition>Slovenia</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>9B7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>ES</value>
						<definition>Spain</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AD7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>SE</value>
						<definition>Sweden</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>B27727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>CH</value>
						<definition>Switzerland</definition>
					</CodeListEntry>
					<CodeListEntry>
						<ccts:UniqueID>AE7727B3-9EEA-E511-80C1-000D3A22E8CD</ccts:UniqueID>
						<value>UK</value>
						<definition>United Kingdom</definition>
					</CodeListEntry>
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name='value' minOccurs='1' maxOccurs='1'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:pattern value='(AT|BE|BG|HR|CY|CZ|DK|EE|FI|FR|DE|EL|HU|IS|IE|IT|LV|LI|LT|LU|MT|NL|NO|PL|PT|RO|SK|SI|ES|SE|CH|UK){1}'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIShortStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A559AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='65' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIInstitutionIDType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>B659AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:pattern value='(AT|BE|BG|HR|CY|CZ|DK|EE|FI|FR|DE|EL|HU|IS|IE|IT|LV|LI|LT|LU|MT|NL|NO|PL|PT|RO|SK|SI|ES|SE|CH|UK|EU):[a-zA-Z0-9]{4,10}' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name='EESSIMediumStringType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>A659AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.CDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
				<xsd:minLength value='1' />
				<xsd:maxLength value='155' />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='EESSIInstitutionType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>2E243C31-9218-E611-80EA-000C292ED0D7</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'institutionID' minOccurs='1' maxOccurs='1' type='sedU021:EESSIInstitutionIDType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>38684F61-9218-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'institutionName' minOccurs='1' maxOccurs='1' type='sedU021:EESSIMediumStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>2AAB0BC6-ACFA-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSILocalCaseNumberType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>C764DE24-529C-E611-80D1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'country' minOccurs='1' maxOccurs='1' type='sedU021:EESSIEUEFTACountryType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>CD64DE24-529C-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'caseNumber' minOccurs='1' maxOccurs='1' type='sedU021:EESSIShortStringType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>6A970F32-539C-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'Institution' minOccurs='0' maxOccurs='1' type='sedU021:EESSIInstitutionType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>6C970F32-539C-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='EESSILocalCaseNumbersType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>C664DE24-529C-E611-80D1-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BIE</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'LocalCaseNumber' minOccurs='0' maxOccurs='unbounded' type='sedU021:EESSILocalCaseNumberType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>D064DE24-529C-E611-80D1-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name='EESSIReimbursementIDType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>BA59AD82-70E5-E711-80DB-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>EESSI.CC.BDT</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base='xsd:string'>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name='ReimbursementFullAcceptanceType'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>7B02E557-3B8A-E611-80D0-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SEDSpecific</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>EESSI</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue></ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'reimbursementRequestID' minOccurs='1' maxOccurs='1' type='sedU021:EESSIReimbursementIDType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>7E02E557-3B8A-E611-80D0-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name='U021'>
		<xsd:annotation>
			<xsd:documentation xml:lang="en">
				<ccts:UniqueID>81FCF16B-45DF-E511-80BF-000D3A22E8CD</ccts:UniqueID>
				<ccts:ObjectClassQualifierTerm>SED</ccts:ObjectClassQualifierTerm>
				<ccts:BusinessProcessContextValue>SED U021</ccts:BusinessProcessContextValue>
				<ccts:OfficialConstraintContextValue>
					
				</ccts:OfficialConstraintContextValue>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name = 'LocalCaseNumbers' minOccurs='0' maxOccurs='1' type='sedU021:EESSILocalCaseNumbersType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>3D960843-4BF8-E611-80D3-000D3A22E8CD</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name = 'ReimbursementFullAcceptance' minOccurs='1' maxOccurs='1' type='sedU021:ReimbursementFullAcceptanceType'>
				<xsd:annotation>
					<xsd:documentation xml:lang="en">
						<ccts:DictionaryEntryName>04D27F85-9518-E611-80EA-000C292ED0D7</ccts:DictionaryEntryName>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="1" ref="ds:Signature"/>
		</xsd:sequence>
		<xsd:attribute name='sedPackage' type='xsd:string' />
		<xsd:attribute name='sedGVer' type='xsd:int' />
		<xsd:attribute name='sedVer' type='xsd:int' />
	</xsd:complexType>
	<xsd:element name='U021' type='sedU021:U021' />
</xsd:schema>